### ISSUE TITLE
run ("Console" <)>; error

### ISSUE THREAD

**Issue by dgraykow** [Eroglu-Lab/Syn_Bot#3]
After applying manual threshold to channels, a Macro Error appears that reads: 

"Unrecognized command: "Console" in line 1788 (called from line 648)

run ("Console"<)>; "

The image file used is a .tif and thresholding works fine but the output has a hard time going through.

**Comment by savagedude3** [comment]
Hello @dgraykow, were you able to resolve this issue? I'd be happy to post the solution in case someone else runs into the same problem in the future.

**Comment by dgraykow** [comment]
Hi Justin,

Yes! I was clicking on circular approximation rather than pixel overlap --
once switching to pixel overlap this resolved the issue.

Very interesting and useful code, quite helpful for quantifying tripartite
synapses. Congrats!

All the best,
David G.

**Comment by savagedude3** [comment]
Good to know. Circular approximation should work for 3-channel analysis, but it is much slower than pixel overlap so I would recommend the pixel overlap for most applications.
