### ISSUE TITLE
Iterating through all group folders

### ISSUE THREAD

**Issue by aradergroves** [Eroglu-Lab/Syn_Bot#6]
Hi! 

This code has been working great, but only seems to iterate through the first group folder at which point the summary csv is saved and the log says "done." The experiment directory I am using is set up as an experiment folder with five group folders, each of which contain 16-50 tif files (still in the piloting stages so they are currently uneven). 

I can run the groups one at a time in separate "experiment" folders, but wanted to see if there was something I was missing that permits all groups to be run in sequence.

Thank you!

**Comment by savagedude3** [comment]
Hi @aradergroves,

I have run some tests and am experiencing the same issue that you describe. You are not doing anything wrong as SynBot is supposed to iterate through the different group folders. Running the groups one at a time should still give you the same results but I will work on a solution.

Thanks for posting this issue!

**Comment by savagedude3** [comment]
I found a missing "}" that seemed to be ending the main for loop on the first experimental group folder instead of going on to the next one. This new release should fix the issue https://github.com/Eroglu-Lab/Syn_Bot/releases/tag/v1.1.3.

**Comment by aradergroves** [comment]
Thanks so much @savagedude3 !
